web/router.ex
defmodule Area91.Router do
  use Area91.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ##########################################
  # Web backend
  ##########################################
  scope "/", Area91 do
    pipe_through :browser # Use the default browser stack

    ### Main
    get "/", MainController, :index
    ### Admin
    resources "/admin/account", AdminAccountController
    resources "/admin/parameter", AdminParameterController
    resources "/admin/currency", AdminCurrencyController
    resources "/admin/market", AdminMarketController
    resources "/admin/product", AdminProductController
    resources "/admin/product_tick_info", AdminProductTickInfoController
    ### General
    get "/version", VersionController, :index
    get "/about", VersionController, :index
    ### Invoice
    resources "/invoice", InvoiceController
    ### Trade
    resources "/trade/journal", TradeJournalController
    get "/trade/financing", TradeFinancingController, :index
    resources "/trade/leverage", TradeLeverageController, only: [:index, :show, :create]
    get "/trade/drawdown", TradeDrawdownController, :index
    ### Import
    resources "/import/accounts", ImportAccountsController
    ### Finance
    resources "/finance/pool", FinancePoolController
    # TODO: Tax export etc. can go here too.
    ### Test
    get "/test", TestController, :index
  end

  ##########################################
  # API backend
  ##########################################
  scope "/api/v1", Area91 do
    pipe_through :api
    #resources "/admin/currency", AdminCurrencyController
    get "/admin/currency", Api.AdminCurrencyController, :index
  end
end

web/templates/finance_drawdown/index.html.eex
<h1 class="centered">Drawdown registration</h1>
<p>
  <form action="<%=finance_drawdown_path(@conn, :drawdown) %>" method="post">
    <div class="form-group">
      <label for="edt_drawdown_current">Current drawdown:</label>
      <input type="text" name="edt_drawdown_current" class="form-control" />
    </div>
  </form>
</p>
  <p>TODO: show max drawdown and pre-fill current drawdown<span class="result"><%=1%></span>. This should be editable for all active trades. Perhaps show a screen inbetween, to choose one to edit?</p>